"""empty message

Revision ID: 292381bf0962
Revises: 92fd4358d8ba
Create Date: 2017-04-22 18:21:08.272292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292381bf0962'
down_revision = '92fd4358d8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    op.drop_column('users', 'avator_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avator_hash', sa.VARCHAR(length=32), nullable=True))
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
