"""empty message

Revision ID: 92fd4358d8ba
Revises: 8a78d1d6522e
Create Date: 2017-04-22 18:15:21.521891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92fd4358d8ba'
down_revision = '8a78d1d6522e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avator_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avator_hash')
    # ### end Alembic commands ###
